POST http://127.0.0.1:8000/login/customer/
Content-Type: application/json

{"email":"can@gmail.com","password":"1234"}

###

POST http://127.0.0.1:8000/signup/customer/
Content-Type: application/json

{   
    "name": "can",
    "tax_id": "1234623763748",
    
    "email": "can@gmail.com",
    "password": "1234",
    "home_address": "canwqkjrdhuwq"
}

###

POST http://127.0.0.1:8000/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTczMTUyOTA0MiwiaWF0IjoxNzMxNDQyNjQyLCJqdGkiOiI2Y2Y3MGJjODE0ZmI0OTc3ODQxZmM5NmVkODIwZGU0YyIsInVzZXJfaWQiOjIwLCJlbWFpbCI6InNlbGltQGdtYWlsLmNvbSJ9.GSbA012oROZFLJmxwf82kRo8i_uLbckMJnhOtnYJaFA"
}

###

GET http://127.0.0.1:8000/test_token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzMyMTE1NjgzLCJpYXQiOjE3MzIxMTIwODMsImp0aSI6IjYwMTkzZTc0MzBmZjRlZjk5MTQwY2QwZGJmNjhkMjliIiwidXNlcl9pZCI6NCwiZW1haWwiOiJjYW4xQGdtYWlsLmNvbSJ9.Qj0xBDKBNMY1Aac7iNLIll8sYo_ccnqwJk7A3x3MY5c

###
POST http://127.0.0.1:8000/products/10/add_comment/
