# Generated by Django 5.1.3 on 2024-11-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoesite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory_to_stock',
        ),
    ]
