# Generated by Django 4.2.16 on 2024-11-02 21:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("shoesite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="popularity_score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(default=40, max_length=10),
        ),
        migrations.CreateModel(
            name="WishlistItem",
            fields=[
                (
                    "wishlist_item_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shoesite.product",
                    ),
                ),
                (
                    "wishlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shoesite.wishlist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                ("refund_id", models.AutoField(primary_key=True, serialize=False)),
                ("request_date", models.DateField(default=django.utils.timezone.now)),
                ("approval_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shoesite.orderitem",
                    ),
                ),
            ],
        ),
    ]
