# Generated by Django 4.2.16 on 2024-11-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
