# Generated by Django 4.2.16 on 2024-11-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoesite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
