# Generated by Django 4.2.16 on 2024-11-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoesite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="customer_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
