# Generated by Django 5.1.3 on 2024-11-20 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoesite', '0002_alter_customer_email'),
        ('shoesite', '0002_remove_product_inventory_to_stock'),
    ]

    operations = [
    ]
