# Generated by Django 4.2.16 on 2024-11-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoesite", "0002_product_description_product_popularity_score_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(max_length=10),
        ),
    ]
