# Generated by Django 4.2.16 on 2024-11-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoesite", "0002_alter_customer_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_id",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
