# Generated by Django 4.2.16 on 2024-11-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoesite', '0002_alter_customer_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='id',
        ),
    ]
