# Generated by Django 4.2.16 on 2024-11-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoesite", "0003_alter_product_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
