# Generated by Django 4.2.16 on 2024-11-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesite', '0003_rename_customer_id_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(max_length=20),
        ),
    ]
