# Generated by Django 4.2.16 on 2024-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shoesite", "0004_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="caegory",
            field=models.TextField(default=""),
        ),
    ]
