# Generated by Django 4.2.16 on 2024-11-04 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shoesite", "0005_product_caegory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="caegory",
            new_name="category",
        ),
    ]
