# Generated by Django 4.2.16 on 2024-11-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesite', '0006_rename_caegory_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
