# Generated by Django 4.2.16 on 2024-11-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoesite', '0008_remove_product_category_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
