# Generated by Django 4.2.16 on 2024-11-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesite', '0012_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(max_length=20),
        ),
    ]
