# Generated by Django 4.2.16 on 2024-11-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesite', '0013_alter_customer_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('sales_manager', 'Sales Manager'), ('product_manager', 'Product Manager')], max_length=20),
        ),
        migrations.AddField(
            model_name='productmanager',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('sales_manager', 'Sales Manager'), ('product_manager', 'Product Manager')], max_length=20),
        ),
        migrations.AddField(
            model_name='salesmanager',
            name='user_type',
            field=models.CharField(blank=True, choices=[('customer', 'Customer'), ('sales_manager', 'Sales Manager'), ('product_manager', 'Product Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='salesmanager',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
