# Generated by Django 4.2.16 on 2024-11-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoesite', '0014_customer_user_type_productmanager_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='productmanager',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='salesmanager',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='productmanager',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salesmanager',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
